version: '3.8'

services:
  app:
    build: .
    container_name: math_app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: math_postgres
    environment:
      POSTGRES_USER: mathuser
      POSTGRES_PASSWORD: mathpass
      POSTGRES_DB: mathdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
